name: "Workflow One"

on: workflow_dispatch

jobs:
  job-one:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Greeting"
        run: echo "Yoooo"
      - name: "Print Goodbye"
        run: echo "Done man"
